version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - redecomunicacao
    environment:
      DB_HOST: db 
      POSTGRES_USER: postgres
      DB_PORT: 5432
      DB_NAME: petshop
      DB_PASSWORD: qwe543210

  db:
    image: postgres
    container_name: petshop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe543210
      PG_HOST: localhost
      PG_NAME: petshop
      PG_PASSWORD: qwe543210
    ports:
      - 5432:5432
    networks:
      - redecomunicacao  
    volumes:
      - ./01-create_database.sql:/docker-entrypoint-initdb.d/01-create_database.sql
      - ./02-insert-users.sql:/docker-entrypoint-initdb.d/02-insert-users.sql

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - 4000:4000
    depends_on:
      - backend
    networks:
      - redecomunicacao  
      
networks:
  redecomunicacao:
    driver: bridge